import type { Metadata } from "next";
import "./globals.css";
import Sider from "./components/Sider";

export const metadata: Metadata = {
    title: "Book App Admin",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="vi">
            <body className='bg-[#292929]'>
                <div className="container mx-auto">
                    <div className="flex items-start">
                        <div className="w-[280px]">
                            <Sider />
                        </div>
                        <div className="flex-1 ml-[20px]">
                            <main className="mt-[30px] mb-[150px]">
                                {children}
                            </main>
                        </div>
                    </div>
                </div>
            </body>
        </html>
    );
}
